version: '3.7'
services:
  db:
    image: postgres:alpine
    container_name: db
    restart: unless-stopped
    volumes:
      - psql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: buzzkhata
    ports:
      - '5432:5432'
  cache:
    image: 'redis:alpine'
    container_name: cache
    restart: unless-stopped
    volumes:
      - redis:/data
    ports:
      - '6379:6379'
  people:
    build: ./
    image: people
    container_name: people
    restart: unless-stopped
    command: npm run dev
    volumes:
      - ./:/usr/src/app/
      - dependencies:/usr/src/app/node_modules
    depends_on:
      - db
    environment:
      CACAHE_URL: redis://cache
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/buzzkhata'
      NODE_ENV: development
    ports:
      - '3000:3000'
volumes:
  dependencies:
  psql:
  redis:
